apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager-capmox
    kind: ClusterSecretStore
  target:
    name: proxmox-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: "{{ .PROXMOX_URL | trim }}"
        token-id: "{{ .PROXMOX_TOKEN | trim }}"
        token-secret: "{{ .PROXMOX_SECRET | trim }}"
  data:
  - secretKey: url
    remoteRef:
      key: "url"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: token-id
    remoteRef:
      key: "token-id"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: token-secret
    remoteRef:
      key: "token-secret"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/proxmox-cluster-cni: null
  name: capmox-cluster-1
spec:
  topology:
    class: proxmox-clusterclass-v0.1.0
    version: v1.29.6
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
      - class: proxmox-worker
        name: proxmox-worker-pool
        replicas: 3
    variables:
    - name: credentialsRef
      value:
        name: proxmox-credentials
    - name: allowedNodes
      value:
      - pve1
      - pve2
    - name: controlPlaneEndpoint
      value:
        host: 172.27.1.3
        port: 6443
    - name: dnsServers
      value: [172.27.1.1]
    - name: ipv4Config
      value:
        addresses: [172.27.1.225-172.27.1.254]
        gateway: 172.72.1.1
        prefix: 24
    - name: cloneSpec
      value:
        machineSpec:
          controlPlane:
            network:
              default:
                bridge: vmbr0
            numSockets: 1
            numCores: 4
            memoryMiB: 4096
            sourceNode: pve1
            templateID: 102
          workerNode:
            network:
              default:
                bridge: vmbr0
            numSockets: 1
            numCores: 4
            memoryMiB: 4096
            sourceNode: pve1
            templateID: 102
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGYxNQegFzQwsFoHirpBYVx2CMSCky0MI9n/H6XbdaU capi@capmox
