apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager-capmox
    kind: ClusterSecretStore
  target:
    name: proxmox-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: "{{ .PROXMOX_URL| trim }}"
        token: "{{ .PROXMOX_TOKEN | trim }}"
        secret: "{{ .PROXMOX_SECRET| trim }}"
  data:
  - secretKey: PROXMOX_URL
    remoteRef:
      key: "PROXMOX_URL"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: PROXMOX_TOKEN
    remoteRef:
      key: "PROXMOX_TOKEN"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: PROXMOX_SECRET
    remoteRef:
      key: "PROXMOX_SECRET"
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/proxmox-cluster-cni: ''
  name: capmox-cluster-1
spec:
  topology:
    class: proxmox-clusterclass-v0.1.0
    version: v1.32.4
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
      - class: proxmox-worker
        name: proxmox-worker-pool
        replicas: 3
    variables:
    - name: skipKubeProxy
      value: true
    - name: credentialsRef
      value:
        name: proxmox-credentials
    - name: allowedNodes
      value:
      - pve2
    - name: controlPlaneEndpoint
      value:
        host: 172.27.1.3
        port: 6443
    - name: dnsServers
      value: [172.27.1.1]
    - name: ipv4Config
      value:
        addresses: [172.27.1.225-172.27.1.254]
        gateway: 172.27.1.1
        prefix: 24
    - name: cloneSpec
      value:
        machineSpec:
          controlPlane:
            network:
              default:
                bridge: vmbr0
            numSockets: 1
            numCores: 2
            memoryMiB: 3192
            sourceNode: pve2
            templateID: 102
          workerNode:
            network:
              default:
                bridge: vmbr0
            numSockets: 1
            numCores: 2
            memoryMiB: 4096
            disks:
              bootVolume:
                disk: scsi0
                sizeGb: 75
            sourceNode: pve2
            templateID: 102
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGYxNQegFzQwsFoHirpBYVx2CMSCky0MI9n/H6XbdaU capi@capmox
