controllerManager:
  manager:
    args:
    - --leader-elect
    - --diagnostics-address=:8443
    - --insecure-diagnostics=false
    - --use-deprecated-infra-machine-naming=false
    - --feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=false,RuntimeSDK=false,MachineSetPreflightChecks=true,MachineWaitForVolumeDetachConsiderVolumeAttachments=true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsGroup: 65532
      runAsUser: 65532
    image:
      repository: registry.k8s.io/cluster-api/cluster-api-controller
      tag: v1.9.4
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
kubernetesClusterDomain: cluster.local
manager:
  serviceAccount:
    annotations: {}
webhookService:
  ports:
  - port: 443
    targetPort: webhook-server
  type: ClusterIP
