---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-provider-core
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: capi-system
  source:
    path: charts/capi-provider-core
    repoURL: https://github.com/stenwt/argo-capi/
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
