
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-api-operator
    server: https://kubernetes.default.svc
  sources:
  - path: ''
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator 
    targetRevision: '0.16.0'
    chart: cluster-api-operator
  - path: 'clusters/capimgr1/extra-manifests/cluster-api-operator'
    repoURL: https://github.com/stenwt/argo-capi
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
