apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capi-provider-capmox.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  {{- include "capi-provider-capmox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-proxmox
      control-plane: controller-manager
    {{- include "capi-provider-capmox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-proxmox
        control-plane: controller-manager
      {{- include "capi-provider-capmox.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        env:
        - name: PROXMOX_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: {{ include "capi-provider-capmox.fullname" . }}-manager-credentials
        - name: PROXMOX_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: {{ include "capi-provider-capmox.fullname" . }}-manager-credentials
        - name: PROXMOX_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: {{ include "capi-provider-capmox.fullname" . }}-manager-credentials
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "capi-provider-capmox.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert