apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capi-provider-capmox.fullname" . }}-manager-credentials
  labels:
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
    platform.ionos.com/secret-type: proxmox-credentials
  {{- include "capi-provider-capmox.labels" . | nindent 4 }}
stringData:
  secret: {{ required "managerCredentials.secret is required" .Values.managerCredentials.secret
    | quote }}
  token: {{ required "managerCredentials.token is required" .Values.managerCredentials.token
    | quote }}
  url: {{ required "managerCredentials.url is required" .Values.managerCredentials.url
    | quote }}