apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-provider-capmox.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  {{- include "capi-provider-capmox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    cluster.x-k8s.io/provider: infrastructure-proxmox
    control-plane: controller-manager
    {{- include "capi-provider-capmox.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}