apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "capi-provider-capmox.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "capi-provider-capmox.fullname" . }}-serving-cert
  labels:
  {{- include "capi-provider-capmox.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "capi-provider-capmox.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-proxmoxcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.proxmoxcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxmoxclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "capi-provider-capmox.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha1-proxmoxmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.proxmoxmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxmoxmachines
  sideEffects: None