apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "capi-provider-core.fullname" . }}-leader-election-role
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  {{- include "capi-provider-core.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "capi-provider-core.fullname" . }}-leader-election-rolebinding
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  {{- include "capi-provider-core.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "capi-provider-core.fullname" . }}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "capi-provider-core.fullname" . }}-manager'
  namespace: '{{ .Release.Namespace }}'