apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capi-provider-core.fullname" . }}-manager
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  {{- include "capi-provider-core.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.manager.serviceAccount.annotations | nindent 4 }}