apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-provider-core.fullname" . }}-webhook-service
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  {{- include "capi-provider-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    cluster.x-k8s.io/provider: cluster-api
    {{- include "capi-provider-core.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}