---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-ssm
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bitwarden-ssm
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://charts.bitwarden.com/
    targetRevision: '0.1.0-Beta'
    chart: sm-operator
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
