---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capimgr1
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: clusters/capimgr1/
    repoURL: https://github.com/stenwt/argo-capi/
    targetRevision: main
  sources: 
  - path: clusters/capimgr1/apps
    repoURL: https://github.com/stenwt/argo-capi/
    targetRevision: main
  - path: clusters/capimgr1/clusters
    repoURL: https://github.com/stenwt/argo-capi/
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true


