---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capimgr1-apps
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  source: 
  - path: appsets
    repoURL: https://github.com/stenwt/argo-capi/
    targetRevision: main
    directory:
      include: "argo-appset.yaml"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true


