---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: capi
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: CAPI
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-operator
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-api-operator
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator 
    targetRevision: '0.14.0'
    chart: cluster-api-operator
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api-clusters
  namespace: 'argocd'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: clusters
    repoURL: https://github.com/stenwt/argo-capi/
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true

