apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
#       selector:
#         matchLabels:
#           argo: "argo-manager"
#       values:
#         env: '{{ index .metadata.labels "env" }}'
#         cloud: '{{ index .metadata.labels "cloud" }}'
    - git:
        repoURL: https://github.com/stenwt/argo-capi.git
        revision: main
        files:
        - path: 'appsets/common/**/argo-config.yaml'
  template:
    metadata:
      name: '{{.app}}-{{.name}}'
    spec:
      destination:
        namespace: '{{ if hasKey . "targetNamespace" }}{{ .targetNamespace }}{{ else }}{{ .app }}{{ end }}'
        name: '{{.name}}'
      sources:
        - repoURL: '{{.chartRepoURL}}'
          chart: '{{.chartName}}'
          targetRevision: '{{.chartVersion}}'
          helm:
            ignoreMissingValueFiles: true
            valueFiles:
            - $values/appsets/common/values/{{.app}}/{{.app}}-values.yaml
            - $values/appsets/common/values/{{.app}}/{{.app}}-{{.chartVersion}}-values.yaml
            - $values/appsets/common/values/{{.app}}/{{.app}}-{{.values.env}}-values.yaml
            - $values/appsets/common/values/{{.app}}/{{.app}}-{{.values.cloud}}-values.yaml
            - $values/appsets/common/values/{{.app}}/{{.app}}-{{.name}}-values.yaml
        - repoURL: https://github.com/stenwt/argo-capi.git
          targetRevision: main
          ref: values
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true